import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Background from "@/components/Background";
import Navbar from "@/components/Navbar";
import skills from "@/data/skills";
import FlipSkillCard from "@/components/FlipSkillCard";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="Portfolio site of Casimir Colas"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <Navbar />
      <div className={styles.socials}>
        <h4>Socials</h4>
        <div className={styles.socialGrid}></div>
      </div>
      <main className={styles.main}>
        <div className={styles.mainContent}>
          <img
            className={styles.pp}
            src="/images/moi.JPG"
            alt="my profile picture"
          />
          <h1 className={styles.name}>Casimir Colas</h1>
          <h2>FULLSTACK web developper</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum
            inventore vel, repellendus fugit sit reprehenderit quos eveniet
            neque ullam quasi beatae soluta repellat ex asperiores, est dicta
            mollitia qui voluptatum!
          </p>
          <div>
            <h3>Known Technologies</h3>
            <p>Hover a card to get more information</p>
            <div className={styles.technoTable}>
              {skills.map((e, index: number) => (
                <FlipSkillCard key={index} {...e} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
